repositories:
    # helm-git powered repository: You can treat any Git repository as a charts repository
    - name: virtualassistant
      url: git+https://{{ requiredEnv "GITHUB_USER" }}:{{ requiredEnv "GITHUB_TOKEN" }}@github.com/DTS-STN/virtual-assistant-mirror@helm/charts?ref=main
   
environments:
    benrd: 
    kylerd:
    adamrd:
    marcusrd:
    ericrd:
    pondrd:
    #USING INT, MAIN AND SPRINT TO REFLECT OUR INTEGRATION (PR VERSION), MAIN (REFLECTING MAIN BRANCH), SPRINT (STATIC RELEASE VERSION FOR SPRINT REVIEW)
    int:
    main:
    sprint:
    prod-blue:
    prod-green: 

releases:
# virtualassistant
  - name: virtualassistant-{{ .Environment.Name }}
    chart: ../helm/charts/virtualassistant
    version: 0.0.1
    values:
      - overrides/virtualassistant.yaml.gotmpl
    labels:
        category: dts
        app: virtualassistant
        tier: server
    namespace: virtualassistant-{{ .Environment.Name }}
    installed: true
    wait: false
    force: false
